services:
  semaphore:
    image: semaphoreui/semaphore:latest
    container_name: semaphore
    restart: always
    ports:
      - "3000:3000"
    environment:
      SEMAPHORE_DB_DIALECT: postgres
      SEMAPHORE_DB_HOST: <your_db_host>
      SEMAPHORE_DB_PORT: 5432
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: <supersecretpassword>
      SEMAPHORE_DB: semaphore
      SEMAPHORE_DB_SSLMODE: disable  # Add this if SSL is not configured
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ADMIN_NAME: "Admin User"
      SEMAPHORE_ADMIN_EMAIL: "admin@example.com"
      SEMAPHORE_ADMIN_PASSWORD: "adminpassword"
    networks:
      - semaphore-net
    volumes:
      - semaphore-data:/etc/semaphore
      - /home/nick/.ssh/ansible_automation_key:/home/semaphore/.ssh/ansible_automation_key:ro # adding ansible automation keys as a RO volume
      - /home/nick/.ssh/ansible_automation_key.pub:/home/semaphore/.ssh/ansible_automation_key.pub:ro # adding ansible automation pub key as a RO volume
volumes:
  semaphore-data:

networks:
  semaphore-net:

# adding a user from the command line
#sudo docker exec -it semaphore semaphore user add \
#  --admin --name "<name>" --login <username> \
#  --password "<supersecretpassword>" --email "<your email>"
